FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY job-collector/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY job-collector/ ./
COPY backend/ /backend/

ENV PYTHONUNBUFFERED=1

CMD ["python", "main.py"]